<?= $this->partial('../app/Views/layouts/header.phtml'); ?>
<main class="page">
  <div class="mdc-toolbar-fixed-adjust"></div>
  <section class="hero" style="height: 100vh;">
    <div id="network" class="hero__image"></div>
  </section>
  <div class="page__content">
    <section>
      <h2 class="mdc-typography--display1">Security Discussion System</h2>
      <p>TBA</p>
    </section>
  </div>
</main>
<script src="/<?= $this->escape($this->appPath); ?>node_modules/material-components-web/dist/material-components-web.js"></script>
<?= $this->partial('../app/Views/layouts/footer.phtml'); ?>
<script src="/<?= $this->escape($this->appPath); ?>scripts/sigma.min.js"></script>
<script src="/<?= $this->escape($this->appPath); ?>scripts/plugins/sigma.parsers.json.min.js"></script>
<script>
  mdc.autoInit()
  sigma.parsers.json('/<?= $this->escape($this->appPath); ?>dmaki.json', {
    container: 'network',
    settings: {
      defaultNodeColor: '#ec5148'
    }
  });
</script>
